name: tests

on: [pull_request, push]

env:
  pnpm: 6

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Cache .pnpm-store
      uses: actions/cache@v1
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-node${{ matrix.node }}-${env.pnpm}-${{ hashFiles('**/pnpm-lock.yaml') }}
    - name: Install pnpm
      run: npm i -g pnpm@${{env.pnpm}}
    - run: pnpm install
    #- run: pnpm run test # skip for now
    - run: pnpm run lint
    - run: pnpm run format
